### ISSUE TITLE
Request: Abstract out pre-compilation for use with any course of notebooks

### ISSUE THREAD

**Issue by ablaom** [jbrea/MLCourse#2]
The apparatus in this repo for creating and saving system images, and then activating them, is *extremely nice*. Have you thought about factoring this out into a general use package for people delivering a course of Pluto (or Jupyter) notebooks? I think this could be very popular.

In more detail:

Suppose I am an instructor who has created a series of notebooks. I want to deploy these as a course like "MLCourse", where students can create and re-use pre-compiled system image (without really needing to understand what they are doing). Can you create a package which makes this painless?

**Comment by jbrea** [comment]
That's an interesting idea. I'll think about it. Would it be useful for you right now?

**Comment by ablaom** [comment]
Yes, provided it was suitably robust 😉 Otherwise, I'd probably fall back to Juptyer notebooks or REPL. What I'm looking for is an environment for delivering short workshops in Julia/MLJ which are:

(i) reliable to install
(ii) have minimum latency issues
(iii) user leaves with an installation on her machine she can use later

**Comment by jbrea** [comment]
I tried very quickly to [factor it out](https://github.com/jbrea/PrecompilePlutoCourse.jl). Please let me know if it is useful for you.

**Comment by ablaom** [comment]
Already got this working at https://github.com/ablaom/HelloJulia.jl/pull/4 (after my PR there). 

Thanks!! 🙏🏾 

I notice you no longer pre-compile as much as before, and in particular don't precompile the plotting libraries. Could you say a little about why?

**Comment by jbrea** [comment]
> I notice you no longer pre-compile as much as before, and in particular don't precompile the plotting libraries. Could you say a little about why?

I wanted to give a minimal example. In MLCourse I still precompile the plotting libraries etc. I added some [instructions](https://github.com/jbrea/PrecompilePlutoCourse.jl#usage) saying that the warmup file could be customized.

**Comment by jbrea** [comment]
PrecompilePlutoCourse is registered now.

**Comment by ablaom** [comment]
Thank you.
